/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 05:16:15 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.FreqTableExampleOriginal;
import java.io.FileNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FreqTableExampleOriginal_ESTest extends FreqTableExampleOriginal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\Miles\\Documents\\GitHub\\CS362-001-SP17\\projects\\daviesmi\\assignment-1\\ciaFactBook2008.txt");
      byte[] byteArray0 = new byte[3];
      byteArray0[1] = (byte) (-6);
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      String[] stringArray0 = new String[7];
      // Undeclared exception!
      try { 
        FreqTableExampleOriginal.main(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 128
         //
         assertThrownBy("edu.osu.cs362.FreqTableExampleOriginal", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\Miles\\Documents\\GitHub\\CS362-001-SP17\\projects\\daviesmi\\assignment-1\\ciaFactBook2008.txt");
      byte[] byteArray0 = new byte[3];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      FileSystemHandling.shouldAllThrowIOExceptions();
      String[] stringArray0 = new String[1];
      FreqTableExampleOriginal.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\Miles\\Documents\\GitHub\\CS362-001-SP17\\projects\\daviesmi\\assignment-1\\ciaFactBook2008.txt");
      String[] stringArray0 = new String[6];
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "nPhS3M)P:pd`2");
      // Undeclared exception!
      try { 
        FreqTableExampleOriginal.main(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 128
         //
         assertThrownBy("edu.osu.cs362.FreqTableExampleOriginal", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      // Undeclared exception!
      try { 
        FreqTableExampleOriginal.createTable((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      try { 
        FreqTableExampleOriginal.createTable("K;=\t%");
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\Miles\\Documents\\GitHub\\CS362-001-SP17\\projects\\daviesmi\\assignment-1\\ ,frequency: ");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      int[] intArray0 = FreqTableExampleOriginal.createTable(" ,frequency: ");
      assertNotNull(intArray0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      int[] intArray0 = FreqTableExampleOriginal.createFreqTableURL(" ,frequency: ");
      assertArrayEquals(new int[] {}, intArray0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      // Undeclared exception!
      try { 
        FreqTableExampleOriginal.createFreqTableURL((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Violation of precondition. parameter url must not be null.
         //
         assertThrownBy("edu.osu.cs362.FreqTableExampleOriginal", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[0];
      FreqTableExampleOriginal.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.utexas.edu/");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "?G]1l zM<m!z-$nV|");
      String[] stringArray0 = new String[7];
      FreqTableExampleOriginal.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FreqTableExampleOriginal freqTableExampleOriginal0 = new FreqTableExampleOriginal();
      assertEquals(128, FreqTableExampleOriginal.NUM_ASCII_CHAR);
  }
}
